[package]
name = "thirteen_server"
version = "0.1.0"
authors = ["Avarel <avarelpm@gmail.com>"]

[dependencies]
rand = "0.4.2"
timer = "0.2.0"
chrono = "0.4.0"
evzht9h3nznqzwl = "0.0.3"
tokio-core = "0.1.12"