[package]
name = "thirteen_server"
version = "0.1.0"
authors = ["Avarel <avarelpm@gmail.com>"]
publish = false

[dependencies]
rand = "0.4.2"
timer = "0.2.0"
chrono = "0.4.0"
ws = "0.7.3"
linked-hash-map = "0.5.1"

serde = "1.0.27"
serde_json = "1.0"
serde_derive = "1.0.27"